FROM pangeo/base-notebook:2023.09.19
# python 3.11
# jsp 4.0.0

ENV PATH=/mnt/cwd:$PATH
RUN <<-EORUN
    set -x

    cat <<-EOF > $(which jupyterhub-singleuser)
        #!/bin/sh
        echo "jupyterhub-singleuser was called!"
    EOF
EORUN
