#!/bin/sh
set -e

cat <<-EOF > $(which jupyterhub-singleuser)
#!/bin/sh
echo "jupyterhub-singleuser was called, and passed \$@"

pip freeze | grep jupyter-server-proxy
conda list jupyter-server-proxy
EOF
