# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
name: Test

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/workflows/*"
      - "!.github/workflows/test.yaml"
  push:
    paths-ignore:
      - "**.md"
      - ".github/workflows/*"
      - "!.github/workflows/test.yaml"
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
  workflow_dispatch:

jobs:
  test:
    name: py${{ matrix.python-version }}-jsp${{ matrix.jsp-version }}_via_${{ matrix.jsp-installed-via }}${{ matrix.test-no-pip }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.7"
            jsp-version: "3"
            jsp-installed-via: pip
          - python-version: "3.8"
            jsp-version: "3"
            jsp-installed-via: pip
          - python-version: "3.8"
            jsp-version: "4"
            jsp-installed-via: pip
          - python-version: "3.11"
            jsp-version: "4"
            jsp-installed-via: pip
          - python-version: "3.9"
            jsp-version: "3"
            jsp-installed-via: conda
          - python-version: "3.11"
            jsp-version: "4"
            jsp-installed-via: conda

    steps:
      - uses: actions/checkout@v4

      - name: Set TAG environment variable
        run: |
          TAG=py${{ matrix.python-version }}-jsp${{ matrix.jsp-version }}-${{ matrix.jsp-installed-via }}
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo $TAG

      - name: Build test image
        run: |
          cd test-images
          docker build . -f Dockerfile.$TAG -t $TAG

      - name: Verify test image
        run: |
          docker run $TAG bash -c 'cat $(which jupyterhub-singleuser)' | grep 'echo "jupyterhub-singleuser was called'

      - name: Run test upgrade
        run: |
          start=`date +%s`
          docker run -e TEST=1 -v $(pwd):/mnt/ghsa-w3vc-fx9p-wp4v $TAG /mnt/ghsa-w3vc-fx9p-wp4v/entrypoint jupyterhub-singleuser --ip=1.2.3.4 > output.txt || true
          end=`date +%s`
          runtime=$((end-start))

          echo "Time to patch: $runtime seconds"

          printf "\nStartup output:\n----------\n\n"
          cat output.txt

          printf "\n\nTests' detected output:\n----------\n\n"
          cat output.txt | grep "__is vulnerable__"
          cat output.txt | grep "jupyterhub-singleuser was called, and passed --ip=1.2.3.4"
          if [[ "${{ matrix.jsp-version }}" == "3" ]]; then
              JSP_VERSION=3.2.2
          else
              JSP_VERSION=4.1.0
          fi
          cat output.txt | grep -A100 "jupyterhub-singleuser was called" | grep $JSP_VERSION
